#!/usr/bin/env bash
# mr-create.sh — Create a merge request (title/description must come from fe-mr-generator)
# Usage: mr-create.sh <project_path_or_id> <source_branch> <target_branch> [options]
#   --title <text>
#   --description <text>   (must contain the fe-mr-generator marker)
#   --assignee-ids <id1,id2>
#   --labels <label1,label2>
#   --draft                (prefix title with "Draft: ")
#   --dry-run

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/_config.sh"

MARKER='<!-- mr:fe-mr-generator -->'

if [[ $# -lt 3 ]]; then
  echo "Usage: $0 <project_path_or_id> <source_branch> <target_branch> [--title <t>] [--description <d>] [--assignee-ids <ids>] [--labels <ls>] [--draft] [--dry-run]" >&2
  exit 1
fi

PROJECT=$(encode_project "$1")
SOURCE_BRANCH="$2"
TARGET_BRANCH="$3"
shift 3

DRY_RUN=0
DRAFT=0
TITLE=""
DESCRIPTION=""
ASSIGNEE_IDS=""
LABELS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --title)         TITLE="$2"; shift 2 ;;
    --description)   DESCRIPTION="$2"; shift 2 ;;
    --assignee-ids)  ASSIGNEE_IDS="$2"; shift 2 ;;
    --labels)        LABELS="$2"; shift 2 ;;
    --draft)         DRAFT=1; shift ;;
    --dry-run)       DRY_RUN=1; shift ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# Enforce fe-mr-generator marker: description must be generated by the skill, not hand-written.
if ! printf '%s' "$DESCRIPTION" | grep -qF "$MARKER"; then
  echo "ERROR: MR description is missing the fe-mr-generator marker." >&2
  echo "先執行 fe-mr-generator skill 產生 title/description，不要手寫。" >&2
  exit 1
fi

# Draft prefix
if [[ "$DRAFT" == "1" ]]; then
  TITLE="Draft: $TITLE"
fi

JSON=$(jq -n \
  --arg sb "$SOURCE_BRANCH" \
  --arg tb "$TARGET_BRANCH" \
  --arg title "$TITLE" \
  --arg desc "$DESCRIPTION" \
  '{source_branch: $sb, target_branch: $tb, title: $title, description: $desc, remove_source_branch: true, squash: false}')

if [[ -n "$ASSIGNEE_IDS" ]]; then
  JSON=$(echo "$JSON" | jq --arg v "$ASSIGNEE_IDS" '. + {assignee_ids: ($v | split(",") | map(tonumber))}')
fi
if [[ -n "$LABELS" ]]; then
  JSON=$(echo "$JSON" | jq --arg v "$LABELS" '. + {labels: $v}')
fi

gitlab_api POST "/projects/$PROJECT/merge_requests" --data "$JSON"
